%%%%%%%%%%%%%%%%%%%% .csv to .mat file %%%%%%%%%%%%%%%%
% This file reads the .csv file generated by Paraview and arranges it to be
% readable by MATLAB

clear; clc; close all;


writerObj = VideoWriter('velocity_field.avi');
writerObj.FrameRate = 2;

open(writerObj);
for i = 1:138
%% specify your file name here
cd G:\computations_dir\rotating_convection\omega0point6_centri;
filename = ['rotating_convection_' num2str(i) '.csv'];
%%

delimiter = ',';
startRow = 2;

formatSpec = '%f%f%f%f%f%f%f%f%f%f%[^\n\r]';
fileID = fopen(filename,'r');

dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);
fclose(fileID);

TimeStep(:,:,i) = dataArray{:, 1};
time(:,:,i) = dataArray{:, 2};
Points0(:,:,i) = dataArray{:, 3};
Points1(:,:,i) = dataArray{:, 4};
Points2(:,:,i) = dataArray{:, 5};
temp(:,:,i) = dataArray{:, 6};
U0(:,:,i) = dataArray{:, 7};
U1(:,:,i) = dataArray{:, 8};
U2(:,:,i) = dataArray{:, 9};
p_var(:,:,i) = dataArray{:, 10};

% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
%% construct a table

augment = [TimeStep(:,:,i),time(:,:,i),Points0(:,:,i),Points1(:,:,i),Points2(:,:,i),temp(:,:,i),U0(:,:,i),U1(:,:,i),U2(:,:,i),p_var(:,:,i)];
%yourtable = array2table(augment);
%sorted_table = sortrows(yourtable,[3 4]);
%sorted_array =table2array(sorted_table);

%%

%x = sorted_array(:,3); y = sorted_array(:,4); 
u_velo = augment(:,7); v_velo = augment(:,8); w_velo = augment(:,9);
u_net = sqrt(u_velo.^2+v_velo.^2+w_velo.^2);

xrange = min(augment(:,3)):0.0005:max(augment(:,3));
yrange = min(augment(:,4)):0.0005:max(augment(:,4));
[xq,yq] = meshgrid(xrange,yrange);

[r,c] = find(u_net == 0);
u_net(r,c) = NaN;
% Interpolate the scattered data on the grid. Plot the results.
veloq_net = griddata(augment(:,3),augment(:,4),u_net,xq,yq);
uq = griddata(augment(:,3),augment(:,4),u_velo,xq,yq);
vq = griddata(augment(:,3),augment(:,4),v_velo,xq,yq);

time_col = time(:,:,i);
time_var = time_col(1,1);

pcolor(xq,yq,veloq_net); shading interp;
xlabel('x [m]');
ylabel('y [m]');
title(['U [m/s], z = 0.04 plane at time = ' num2str(time_col(1,1)) 's']);
colorbar;
caxis([0 0.02]);

hold on;
parameter = 10;
quiver(xq((1:parameter:end),(1:parameter:end)),yq((1:parameter:end),(1:parameter:end)),uq((1:parameter:end),(1:parameter:end)),vq((1:parameter:end),(1:parameter:end)),2,'k');

axis square;
axis tight;


colormap(parula);
writeVideo(writerObj, getframe(gcf));

indices = find(int8(isnan(uq)) == 1);
uq(indices) = 0;
vq(indices) = 0;

cd G:/computations_dir/ftle_dir/rotating_convection/data/TBarrier/2D/data/rotating_convection;
save(['rotating_convection_' sprintf('%03d ',i) '.mat'],'xq','yq','time_var','uq','vq');
end
close(writerObj);
%%


    

    


